# Generated by Django 5.2.3 on 2025-07-02 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep_origem', models.CharField(max_length=8)),
                ('origem_cidade', models.CharField(max_length=150)),
                ('origem_estado', models.CharField(max_length=150)),
                ('data_ida', models.DateField()),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moeda_destino', models.CharField(max_length=10)),
                ('cotacao', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
