# Generated by Django 5.2.3 on 2025-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='destino',
            field=models.CharField(default='Brasil', max_length=100),
            preserve_default=False,
        ),
    ]
