# Generated by Django 5.2.3 on 2025-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255, unique=True)),
                ('moeda', models.CharField(max_length=255)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
