# Generated by Django 5.2.3 on 2025-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='codigo_iso',
            field=models.CharField(max_length=3),
        ),
    ]
